---
name: jaffle_shop

config-version: 2
version: 0.0.0
require-dbt-version: [">=1.4.0", "<1.5.0"]

profile: default

model-paths: ["jaffle_shop/models"]
seed-paths: ["jaffle_shop/seeds"]
test-paths: ["jaffle_shop/tests"]
macro-paths: ["jaffle_shop/macros"]

target-path: target
packages-install-path: &packages "jaffle_shop/packages"
clean-targets: [logs, target, *packages]

quoting:
  database: false
  schema: false
  identifier: false

models:
  jaffle_shop:
    +materialized: table
    +schema: main

seeds:
  +docs:
    node_color: Gray

tests:
  +docs:
    node_color: Indigo
